DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS teams;

CREATE TABLE teams (
  id SERIAL PRIMARY KEY,
  team_name VARCHAR(255)
);

CREATE TABLE matches (
  id SERIAL PRIMARY KEY,
  -- home_team VARCHAR(255) NOT NULL,
  -- away_team VARCHAR(255) NOT NULL,
  home_team INT REFERENCES teams(id) ON DELETE CASCADE,
  away_team INT REFERENCES teams(id) ON DELETE CASCADE,
  result VARCHAR(255)
);
